version: "3"

x-nx-env-volume:
  &nx-env
  type: bind
  source: ./config/env/.env.${NX_APP_ENV:-dev}
  target: /usr/src/root/.env

x-nx-tools-volume:
  &nx-tools
  type: bind
  source: ./tools
  target: /usr/src/root/tools

x-nx-libs-volume:
  &nx-libs
  type: bind
  source: ./libs
  target: /usr/src/root/libs

x-nx-node-modules-volume:
  &nx-node-modules
  type: bind
  source: ./node_modules
  target: /usr/src/root/node_modules

services:
  nx-base:
    volumes:
      - *nx-env
      - *nx-tools
      - *nx-libs
      # - *nx-node-modules
