version: "3"

# @INFO: The application only runs the UI (client-app - React).
services:
  clientapp:
    extends:
      file: docker-compose.base.yaml
      service: nx-base
    build:
      dockerfile: ./apps/client-app/Dockerfile.dev
    volumes:
      - ./apps/client-app/:/usr/src/root/apps/client-app
    ports:
      - '4200:4200'
