FROM node:16.17.0-alpine

WORKDIR '/tmp'
COPY ./tools/dev-scripts/cmd-pnpm-install.sh ./
RUN chmod +x ./cmd-pnpm-install.sh && /bin/sh ./cmd-pnpm-install.sh

WORKDIR '/usr/src/root'
COPY ./package.json ./pnpm-lock.yaml ./pnpm-workspace.yaml ./.npmrc ./
COPY ./apps/api-core/package.json ./apps/api-core/
RUN pnpm install
COPY . .
RUN node ./tools/dev-scripts/cmd-pre-pnpm-install.js api-core
CMD ["pnpm", "docker:api-core"]
