FROM node:16.17.0-alpine
WORKDIR '/usr/src/root'
RUN npm install -g pnpm
# Copy is put before install intentionally. 'COPY . .' only copies the package.json files of the projects. Rest is seperately mounted.
COPY ./package.json ./pnpm-lock.yaml ./pnpm-workspace.yaml ./.npmrc ./
COPY ./apps/client-app/package.json ./apps/client-app/
RUN pnpm install
COPY . .
RUN node ./tools/dev-scripts/cmd-pre-pnpm-install.js client-app
CMD ["pnpm", "docker:client-app"]
