name: build

on:
  workflow_dispatch:
    inputs:
      # Sha: Git sha. If not provided the system will default to the HEAD of the branch
      sha:
        description: 'Sha: Commit sha to build from.'
        required: false
      apps:
        description: 'Apps: (Write a list of apps to build. Ex: ["client-app", "api-core"]). Empty array creates images for all services.'
        default: '[]'
        required: false
  push:
    tags:
      - '*'

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ACR_ENDPOINT: ${{ secrets.ACR_ENDPOINT }}
  ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
  ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
  NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
  NX_BRANCH: ${{ github.head_ref || github.ref_name }}

jobs:
  set-inputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.17.0"
      - name: Generate inputs
        id: generate-inputs
        run: |
          # INPUT -> Apps
          echo "apps=$(node tools/dev-scripts/cmd-get-build-projects.js '${{inputs.apps}}')" >> $GITHUB_OUTPUT

          # INPUT - Sha
          if [[ "${{inputs.sha}}" == "" ]]; then
            echo "sha=$(git rev-parse "$GITHUB_SHA")" >> $GITHUB_OUTPUT
          else
            echo "sha=${{ inputs.sha }}" >> $GITHUB_OUTPUT
          fi

          # INPUT - Branch
          echo "branch=${{ github.head_ref || github.ref_name }}" >> $GITHUB_OUTPUT
      - name: Print inputs
        run: |
          echo "APPS: ${{ steps.generate-inputs.outputs.apps }}"
          echo "SHA: ${{ steps.generate-inputs.outputs.sha }}"
          echo "BRANCH: ${{ steps.generate-inputs.outputs.branch }}"
    outputs:
      apps: ${{ steps.generate-inputs.outputs.apps }}
      sha: ${{ steps.generate-inputs.outputs.sha }}
      branch: ${{ steps.generate-inputs.outputs.branch }}
  build:
    runs-on: ubuntu-latest
    needs: [set-inputs]
    if: ${{ fromJson(needs.set-inputs.outputs.apps)[0] }}
    strategy:
      max-parallel: 4
      matrix:
        node: ["16.17.0"]
        projectName: ${{fromJson(needs.set-inputs.outputs.apps)}}
    env:
      NODE: ${{ matrix.node }}
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: "7.x"
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
      - name: Install dependencies
        # @INFO: Don't install only prod dependencies. Dev dependencies are needed to use the nx build and cloud.
        run: pnpm install
      - name: Build
        run: |
          git checkout ${{needs.set-inputs.outputs.sha}}
          pnpm nx run ${{ matrix.projectName }}:build
          rm -rf ./apps/${{matrix.projectName}}/dist
          # @INFO: For now skip the api-worker and e2e builds, since it is not being used. Skipping is done inside the 'cmd-get-build-projects.js' script
          cp -r ./dist/apps/${{matrix.projectName}}/ ./apps/${{matrix.projectName}}/dist/
      - name: Version
        id: version
        run: |
          VERSION="$(git tag --points-at ${{needs.set-inputs.outputs.sha}})"

          # If there is no version set the version to the tag ref
          if [[ $VERSION == "" ]]; then
            VERSION="$GITHUB_REF_NAME"
          fi

          # If there is still no version set the version to sha
          if [[ $VERSION == "" ]]; then
            VERSION="${{needs.set-inputs.outputs.sha}}"
          fi

          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Package
        run: |
          IMAGE_NAME="${{matrix.projectName}}"
          VERSION="${{steps.version.outputs.version}}"
          TAG="$ACR_ENDPOINT/$IMAGE_NAME:$VERSION"
          # - Docker login
          echo $ACR_PASSWORD | docker login $ACR_ENDPOINT -u $ACR_USERNAME --password-stdin
          # - Docker build
          docker build -t $TAG -f ./apps/${{matrix.projectName}}/Dockerfile ./apps/${{matrix.projectName}}
          # - Docker push
          docker push $TAG
